### ISSUE TITLE
Adding performance data?

### ISSUE THREAD

**Issue by kso512** [glensc/nagios-plugin-check_domain#18]
Hello Elan and fellow users,

I would like to discuss appending performance data, changing the output from this:

    $ ./check_domain.sh -d github.com -w 30 -c 10
    OK - Domain github.com will expire in 2056 days (2020-10-09).

to something like this:

    $ ./check_domain.sh -d github.com -w 30 -c 10
    OK - Domain github.com will expire in 2056 days (2020-10-09).|days=2056;30;10;0;

This would move the plugin from Case 1 to Case 2 as defined by the [Nagios Plugin API](http://nagios.sourceforge.net/docs/3_0/pluginapi.html) and uses the format:

    |varname=value;warning;critical;min;max

Some options for implementation could be:
* Adding a new command line option set (for example: "-p|--perfdata") 
  * _Might be confused with -P, so -f or something else might be better?_
* Making it the default for the current script
  * _If this doesn't break any current usage, it would enhance the plugin by adding graphs to systems like Check_MK that utilize performance data automatically._
* Adding a new script that appends the performance data as the default
  * _Avoids issues above, but wastes space & effort._

As none of the above seem non-trivial, I figured it would be best to discuss this with you and the community before I went too far down any of these roads, since I would hope to eventually have the code mainlined.

Thanks for making this great plugin!

**Comment by Elyrith** [comment]
From https://nagios-plugins.org/doc/guidelines.html#AEN200
It says min and max are optional if UOM is '%', but the min can be lower than 0 for expired domains

If we add min and max, I propose either 4017 or 3652 for the max. According to Wikipedia (http://en.wikipedia.org/wiki/Domain_name_registrar#Designated_registrar, last paragraph) domains can be officially registered for a maximum of 10 years. 
365 days * 10 years + 3 maximum leap years + 364 (current year) = 4017 days (?)
Or, if the current year is included in the '10 years' then 4017-365=3652

I haven't done enough research to know which one would be correct.

**Comment by glensc** [comment]
#21 got merged meanwhile. i have no opinion in this. let  the community decide what's the best.

**Comment by kso512** [comment]
Thanks Elyrith & glesc, awesome work!

You're absolutely right about the minimum value, and for now I think leaving it and the maximum off is perfect.

As it's part of the Nagios standard, making it the default action shouldn't break anything, and it is working in my tests so far without issue.

Note 6 in the Nagios Plugins performance data guidelines linked by Elyrith (great link! :D) states they are all optional:

"warn, crit, **min** or **max** may be null (for example, if the threshold is not defined or min and max do not apply). Trailing unfilled semicolons can be dropped"

Thanks again for your efforts!!

**Comment by glensc** [comment]
can this be closed now?

**Comment by kso512** [comment]
Ah yes, I hit the wrong button...!  

Closing now, thanks again!
