### ISSUE TITLE
Update for check_domain.sh to add for .pt tld

### ISSUE THREAD

**Issue by nevilleonline** [glensc/nagios-plugin-check_domain#19]
Would you be able to add for autoproff.pt domain

whois autoproff.pt
[Querying whois.dns.pt]
[whois.dns.pt]
Nome de domínio / Domain Name: autoproff.pt
Data de registo / Creation Date (dd/mm/yyyy): 19/01/2015
Data de expiração / Expiration Date (dd/mm/yyyy): 18/01/2016
Estado / Status: ACTIVE

Titular / Registrant
XXXXXXX
XXXXXXX
XXXXXXX
Email: XXXXXXX

Entidade Gestora / Billing Contact
EPAG Domainservices GmbH
Email: XXXXXXX

Responsável Técnico / Tech Contact
EPAG Domainservices GmbH
Email: XXXXXXX

Nameserver Information
Nameserver: autoproff.pt NS ns4.gratisdns.dk.
Nameserver: autoproff.pt NS ns1.gratisdns.dk.
Nameserver: autoproff.pt NS ns2.gratisdns.dk.
Nameserver: autoproff.pt NS ns5.gratisdns.dk.
Nameserver: autoproff.pt NS ns3.gratisdns.dk.

This one also include expiry date information (Data de expiração / Expiration Date (dd/mm/yyyy): 18/01/2016). Thanks

**Comment by nevilleonline** [comment]
Hi ,

I am not sure but the script for pt tld domain is not working,

[root@monitor nagios-plugin-check_domain-master]# ./check_domain.sh -d autoproff.pt
awk: cmd. line:90: warning: escape sequence `\(' treated as plain `('
awk: cmd. line:90: warning: escape sequence `\)' treated as plain `)'
UNKNOWN - Unable to figure out expiration date for autoproff.pt Domain.

**Comment by glensc** [comment]
ah the awk differences. can you give me details of your "awk"

**Comment by glensc** [comment]
sadly all awk versions from travis (ubuntu packages) do pass the tests:

https://travis-ci.org/glensc/nagios-plugin-check_domain/builds/55611418

so this got unnoticed by me

**Comment by glensc** [comment]
looks like original awk take `\(` for literal `(`, whilst gnu-awk need plain `(`

**Comment by nevilleonline** [comment]
Hi Glen,

I am using Centos 6.6 OS and I have the below version of awk installed.
[root@monitor ~]# rpm -qa *awk*
gawk-3.1.7-10.el6.x86_64

Let me know if you need any more info.

**Comment by glensc** [comment]
should be solved already. check out new version!
