### ISSUE TITLE
Rate limiting options or workarounds?

### ISSUE THREAD

**Issue by mxroo** [glensc/nagios-plugin-check_domain#29]
Thank you @oasys for updating the script to make rate limited responses unknown again as opposed to critical in #28, that helped a lot! 

My issue is that I'm checking over 100 domains for my clients and most of my clients have .org addresses so I've been coming up against the domain limiting for years.

Has anyone figured out a way to completely avoid it either in the plugin code or in nagios/icinga settings?

I use Icinga 1.11.6, and I've tried telling Icinga to allow more failures, check only twice per 24 hours, max_service_check_spread set to 180 minutes to spread out initial checks, and still pir.org's rate limiting logic stymies me.

Thanks in advance.

**Comment by oasys** [comment]
Glad to help.

The way the plugin works is to do all the queries at once.  One could certainly add functionality to rate limit the queries (I'd probably use a simple sleep mechanism), but you would have to be concerned about the total run-time of the plugin.  I'm not sure if that is an issue for Icinga.

I've found that the pir.org limit is quite low -- something on the order of 5 queries in 10 seconds (their website says "four queries per minute.") -- but it also resets quickly.  We only have a handful of .org's to test, so it picks up fine on the second check. Having it transition to UNKNOWN is only a minor annoyance for my installation.

Solving this in a more generic way for hundreds of domains spread across multiple different whois servers with varying rate-limit thresholds doesn't seem straightforward to me.  Maybe it would be good enough just to add a "sleep" command line option to the script (to wait between queries), and then you could divide your check into .org and non-.org domains, running the former with an appropriate speed command?  For the number of domains you cite, that would still take over a half hour to run.

Other options I can think of would be to spread queries across multiple source IP's, or to ask pir.org operators to whitelist your network.

**Comment by glensc** [comment]
but check_domain with different domains is not called in serial, how Nagios/Icinga spreads the checks for each domain is not very predictable.

you do have separate check for each domain in question?

**Comment by mxroo** [comment]
@oasys I'm afraid there is no way I could see to ask pir.org to whitelist, that pir.org is the only whois for .org domains, and I only have the one icinga server with one IP running the checks.

@glensc Yes, there are separate checks for each domain. I've attempted to have it spread the checks out, but pir.org's rate limiting seems to be even stricter than 4/minute.

Thanks!

**Comment by mxroo** [comment]
I've posted as well to the Icinga-users list (https://lists.icinga.org/pipermail/icinga-users/2015-April/009446.html), but I've gotten no responses. If anyone has any ideas, I'm at a bit of a loss. I've even tried calling PIR, but the voicemail box was full.

**Comment by Elyrith** [comment]
(Note: I've only used Nagios.)

While not exactly a fix, depending on how low you are setting the $warning and $critical values you may find it's okay to have Nagios/Icinga only check each domain once every couple of days (as long as the status is 'OK').

Example: You have 100 domains and you want a warning when expiration is 30 days away and critical at 7, it's (probably) not super-important that you know you only have 30 days left. It's (probably) fine to know when you have 28 days left. This way you can set your checks to every 2 or 3 days (to be slightly adjusted by randomization by Nagios). This way you are only checking one domain every ~30 or ~45 minutes, respectively.

Alternatively, is it possible for you to have a warning at 60 days and critical at 30, then only check every 7 days?

If there's a reason you can't do this, then obviously this won't work. :smile_cat: 
I only check ~10 domains and I set them to check once a day (each), so I'm in a different situation.

**Comment by mxroo** [comment]
@Elyrith That is a totally helpful idea, but I am already doing most of that I'm afraid. I'm to the point where it is only checking twice per day, and only notifies me if it's a problem after failing for 5 days in a row, but still, they fail. One of the issues is the initial scheduling of checks clumps them together, and the other is that I'm definitely getting blocked by PIR but checking less than once per minute.

**Comment by Elyrith** [comment]
@mxroo I meant something more like this:
(assuming your interval_length=60 in nagios.cfg)

```
# Check every 3 days
	normal_check_interval	4320
# Retry every 60 minutes
	retry_check_interval	60
# Notify after 6 consecutive fails
	max_check_attempts		6
```

(I added the comments for anybody reading this in the future.)

---

There are two problems I can think of with adding rate-limiting to check_domain:

1. The script doesn't know when it was last run, so it has no way to determine if it's running too soon after the last time, (but possibly more importantly...)
2. If the script determined it is running too soon it has no way to exit gracefully. Plugins are forced to return a value [between 0 and 3](http://nagios.sourceforge.net/docs/3_0/pluginapi.html). What would you return if you hit the rate limit?
  1. OK: If a particular domain is unlucky and is always seeing "RATE LIMIT REACHED" you'll never know when it's going to expire, or
  2. UNKNOWN: This is functionally equivalent to how it works now.

The only alternative I can think of is to use a different method of checking the domain status with caching or time logging or something and submitting passive checks to Nagios.

**Comment by mxroo** [comment]
@Elyrith oh excellent! I'll give that a try and report back. I will say that checks are completely failing now, but I have a ticket open with PIR.org

**Comment by Elyrith** [comment]
@mxroo Out of curiosity, which option are you going to try? :D

**Comment by mxroo** [comment]
Changing the settings for those checks to be:

```
# Check every 3 days
    normal_check_interval   4320
# Retry every 60 minutes
    retry_check_interval    60
# Notify after 6 consecutive fails
    max_check_attempts      6
```

If that doesn't work and PIR doesn't get back to me with anything helpful, I will look into caching the results locally or paying for a paid whois service.

**Comment by Elyrith** [comment]
@mxroo Do you have any updates on this?

**Comment by mxroo** [comment]
@Elyrith tl;dr all better now, IPv6 problem on PIR's end

Changing the checks to use that helped a lot, and made all non .org checks work perfectly, but .org checks were still all getting dropped. The issue was that for some reason my server was trying to use PIR's whois server (whois.publicinterestregistry.net) using its IPv6 address, but getting bounced. I had a long phone call with a tech working for PIR and we figured out from the verbose telnet command that my server was trying on IPv6. When I attempted on IPv4 it worked. So I told my server to prefer IPv4 addresses for now using `precedence ::ffff:0:0/96 100` in /etc/gai.conf and it's been working perfectly since. The tech I talked to was surprised that their systems weren't supporting IPv6 and agreed with me that that wasn't a long term solution, so they get to work on that, and I get to close this ticket.

**Comment by Elyrith** [comment]
@mxroo Nice work with PIR! I never would have suspected the problem with IPv6.
I'm glad everything's working now. :smile_cat:

**Comment by glensc** [comment]
i was thinking that `check_domain` could add `-4` and `-6` options to force `ipv4` or `ipv6`, but i do not see any commandline option to force `whois` client to do so.

**Comment by mxroo** [comment]
@glensc yup. I found that in my research as well, which is why I unfortunately decided to just set the preference system wide.
