### ISSUE TITLE
Support for .com.cn and .cn tlds

### ISSUE THREAD

**Issue by nevilleonline** [glensc/nagios-plugin-check_domain#31]
Hi,

Kindly add support for .com.cn and .cn tlds. Expiration date format is given below for the 2 domains.

 [root@monitor ~]#whois gogovcard.com.cn
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
Domain Name: gogovcard.com.cn
ROID: 20150218s10011s84514959-cn
Domain Status: clientTransferProhibited
Registrant ID: p44023925
Registrant: MARCARIA NETWORK LTD
Registrant Contact Email: domains@marcaria.com
Sponsoring Registrar: å¹¿ä¸æ¶ä»£äºèç§ææéå
¬å¸
Name Server: ns01.trademarkarea.com
Name Server: ns02.trademarkarea.com
Registration Time: 2015-02-18 05:14:08
Expiration Time: 2016-02-18 05:14:08
DNSSEC: unsigned

[root@monitor ~]# whois gogovcard.cn
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
Domain Name: gogovcard.cn
ROID: 20150218s10001s73956434-cn
Domain Status: clientTransferProhibited
Registrant ID: p44023925
Registrant: MARCARIA NETWORK LTD
Registrant Contact Email: domains@marcaria.com
Sponsoring Registrar: å¹¿ä¸æ¶ä»£äºèç§ææéå
¬å¸
Name Server: ns01.trademarkarea.com
Name Server: ns02.trademarkarea.com
Registration Time: 2015-02-18 05:14:09
Expiration Time: 2016-02-18 05:14:09
DNSSEC: unsigned

**Comment by glensc** [comment]
merged via #40, thanks @Elyrith!
