### ISSUE TITLE
io domains are not getting results

### ISSUE THREAD

**Issue by bbhenry** [glensc/nagios-plugin-check_domain#45]
I was able to do the following to get expiration date on .io domains, but since it's a popular one, can you have the lookup host build into the script?

```
./check_domain.sh -s whois.nic.io -d zeeto.io
```

**Comment by Elyrith** [comment]
My opinion is not that of the maintainer of this script, of course, but I don't think specially hard-coding the .io server is likely when that's the whole reason the -s switch exists. :smile:

**Comment by glensc** [comment]
thanks @Elyrith!

i think you should [report this to whois](https://github.com/rfc1036/whois/issues/new) program. as that is where the default servers are declared.
