### ISSUE TITLE
Error "fgets: Connection reset by peer" breaks the parsing

### ISSUE THREAD

**Issue by Elyrith** [glensc/nagios-plugin-check_domain#47]
Occasionally when running a whois the command gets the output we need (with the expiration date, etc.), but a separate part of the request the whois server queried gets denied with the error "fgets: Connection reset by peer"

This means we get our info, but because an error is thrown this line in check_domain.sh means we exit with error 2 instead of continuing to parse the data:

[ $error -eq 0 ] || die "$STATE_UNKNOWN" "UNKNOWN - WHOIS exited with error $error."

**Comment by Elyrith** [comment]
This is the output I get when I run the whois command for my domain (with my domain removed)...

Whois Server Version 2.0

Domain names in the .com and .net domains can now be registered
with many different competing registrars. Go to http://www.internic.net
for detailed information.

   Domain Name: DOMAIN.COM
   Registrar: GODADDY.COM, LLC
   Sponsoring Registrar IANA ID: 146
   Whois Server: whois.godaddy.com
   Referral URL: http://registrar.godaddy.com
   Name Server: NS05.DOMAINCONTROL.COM
   Name Server: NS06.DOMAINCONTROL.COM
   Status: clientDeleteProhibited http://www.icann.org/epp#clientDeleteProhibited
   Status: clientRenewProhibited http://www.icann.org/epp#clientRenewProhibited
   Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
   Status: clientUpdateProhibited http://www.icann.org/epp#clientUpdateProhibited
   Updated Date: 18-apr-2015
   Creation Date: 05-feb-2004
   Expiration Date: 05-feb-2016

>>> Last update of whois database: Mon, 19 Oct 2015 04:16:52 GMT <<<

NOTICE: The expiration date displayed in this record is the date the 
registrar's sponsorship of the domain name registration in the registry is 
currently set to expire. This date does not necessarily reflect the expiration 
date of the domain name registrant's agreement with the sponsoring 
registrar.  Users may consult the sponsoring registrar's Whois database to 
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois 
database through the use of electronic processes that are high-volume and 
automated except as reasonably necessary to register domain names or 
modify existing registrations; the Data in VeriSign Global Registry 
Services' ("VeriSign") Whois database is provided by VeriSign for 
information purposes only, and to assist persons in obtaining information 
about or related to a domain name registration record. VeriSign does not 
guarantee its accuracy. By submitting a Whois query, you agree to abide 
by the following terms of use: You agree that you may use this Data only 
for lawful purposes and that under no circumstances will you use this Data 
to: (1) allow, enable, or otherwise support the transmission of mass 
unsolicited, commercial advertising or solicitations via e-mail, telephone, 
or facsimile; or (2) enable high volume, automated, electronic processes 
that apply to VeriSign (or its computer systems). The compilation, 
repackaging, dissemination or other use of this Data is expressly 
prohibited without the prior written consent of VeriSign. You agree not to 
use electronic processes that are automated and high-volume to access or 
query the Whois database except as reasonably necessary to register 
domain names or modify existing registrations. VeriSign reserves the right 
to restrict your access to the Whois database in its sole discretion to ensure 
operational stability.  VeriSign may restrict or terminate your access to the 
Whois database for failure to abide by these terms of use. VeriSign 
reserves the right to modify these terms at any time. 

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.

For more information on Whois status codes, please visit 
https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en.
fgets: Connection reset by peer

**Comment by Elyrith** [comment]
I've created a patch to ignore error 2, which I hope is only this fgets error. I'll create a pull request momentarily.

**Comment by Elyrith** [comment]
Hey Elan, is this patch okay or is there anything I'm missing?

**Comment by glensc** [comment]
it was forgotten, checking now.

seems the last commit is something bogus, will merge without that last commit

**Comment by Elyrith** [comment]
It looks like I ran it through shellcheck.net and committed it to the wrong branch by accident in that last commit. Sorry.
