### ISSUE TITLE
Run check_domain.sh through shellcheck.net

### ISSUE THREAD

**Issue by Elyrith** [glensc/nagios-plugin-check_domain#49]
Hey Elan, as you know I'm not that strong of a coder, but I get by (barely). For a few years I've occasionally used the shellcheck.net website to verify that my code is good for shell scripts.

I ran check_domain.sh through it and there were a few issues it found. Nothing major, of course.

Would you find it valuable if I went through the results and submitted a PR with an updated version with help from that site?

**Comment by glensc** [comment]
yes, why not. i run some lint too time to time, and new issues slip trough pull requests, and i probably don't know every glitch out there either.

**Comment by Elyrith** [comment]
Merged and completed. Closing issue.
