### ISSUE TITLE
unable to get expiration date for co.nz and GoDaddy's domains

### ISSUE THREAD

**Issue by kolyan007** [glensc/nagios-plugin-check_domain#54]
# /usr/local/nagios/libexec/check_domain.sh -w 30 -c 10 -d stuff.co.nz
UNKNOWN - Unable to figure out expiration date for stuff.co.nz Domain.

# /usr/local/nagios/libexec/check_domain.sh -w 30 -c 10 -d trademe.co.nz
UNKNOWN - Unable to figure out expiration date for trademe.co.nz Domain.

# /usr/local/nagios/libexec/check_domain.sh -w 30 -c 10 -d pricespy.co.nz
UNKNOWN - Unable to figure out expiration date for pricespy.co.nz Domain.

**Comment by Elyrith** [comment]
I cannot replicate these results. Are they still not working for you, @kolyan007?

---
`check_domain.sh -d stuff.co.nz -w 30 -c 10`
`OK - Domain stuff.co.nz will expire in 76 days (2016-05-02). | domain_days_until_expiry=76;30;10`

---
`check_domain.sh -d trademe.co.nz -w 30 -c 10`
`OK - Domain trademe.co.nz will expire in 325 days (2017-01-06). | domain_days_until_expiry=325;30;10`

---
`check_domain.sh -d pricespy.co.nz -w 30 -c 10`
`OK - Domain pricespy.co.nz will expire in 355 days (2017-02-05). | domain_days_until_expiry=355;30;10`

**Comment by kolyan007** [comment]
Not relevant anymore.
